fix: create git branch if does not exist locally
to avoid error:

```
> git checkout latest

error: pathspec 'latest' did not match any file(s) known to git
```

if you pass in a branch (in our example above it's latest) that does not exist locally.